export default {"blogs":[
  {"company":[
    {"id":1,
      "name":"WildAlmonds",
      "type":"winereviews",
      "slug":"wildalmonds",
      "image_path":null}
    ]
  },
    {"game":[
        {"game_id":"f0b0aaa7-5dc2-43b5-b898-dda9c9fcb8ab","game_name":"Woodinville Wine Country"},
        {"game_id":"8bf93ce8-9152-4dcc-a219-e83bcb1378a7","game_name":"Snohomish Wine Walk June '23"},
        {"game_id":"b372e158-0c09-4d8b-81f0-b0bea41665c7","game_name":"Kirkland Pride June '23"},
        {"game_id":"0929d52d-40c3-4a7e-b579-6d6faf637da1","game_name":"Edmonds Summer Wine Walk"},
        {"game_id":"885d9f30-6683-4c7c-8c7a-c9eab2eba02a","game_name":"Kingston Wine & Brew Fest"},
        {"game_id":"9997713b-6a40-42f2-b1b0-421bd3f61b01","game_name":"Edmonds Wine Walk 08_23"},
        {"game_id":"a69a2177-45a0-4e21-acc1-6939d0976825","game_name":"Redmond Wine Walk"},
        {"game_id":"c6b2232a-b9b7-450d-a605-c0882afd26ca","game_name":"Snohomish Wine Walk Sept 9th 2023"},
        {"game_id":"f9f0d166-a9dc-4e1d-ba1b-47a737ea9cb0","game_name":"Home"}
      ]
    },
    {"squares":"ER_SUBQUERY_NO_1_ROW: Subquery returns more than 1 row"},
    {"blogList":[
      {"id":40,
        "title":"Wine Judging 101",
        "blog":"Blog text for ID 40",
        "author":21,
        "createdAt":"2023-10-09T21:27:41.000Z",
        "status":"active",
        "image_path":null,
        "firstname":"Andrew",
        "lastname":"Reid"
      },
      {id:33,
        "title":"Snohomish Wine Walk Sept 9th, 2023",
        "blog": "Blog text for ID 33",
        "author":21,
        "createdAt":"2023-08-11T17:44:06.000Z",
        "status":"active",
        "image_path":null,
        "firstname":"Andrew",
        "lastname":"Reid"
      },
      {"id":32,
        "title":"August Wine Walks",
        "blog": "Text for Blog Id #32",
        "author":21,
        "createdAt":"2023-08-02T18:16:42.000Z",
        "status":"active",
        "image_path":null,
        "firstname":"Andrew",
        "lastname":"Reid"
      },
      {"id":29,
        "title":"Kingston Wine and Brew Fest",
        "blog": "Blog text for ID 29",
        "author":21,
        "createdAt":"2023-07-08T16:42:27.000Z",
        "status":"active",
        "image_path":null,
        "firstname":"Andrew",
        "lastname":"Reid"
      },
      {"id":28,
        "title":"Woodinville Wine Tasting",
        "blog": "Text for Blog Id #28",
        "author":21,
        "createdAt":"2023-05-31T15:20:25.000Z",
        "status":"active",
        "image_path":null,
        "firstname":"Andrew",
        "lastname":"Reid"
      },
      {"id":27,
        "title":"Bubbles from Woodinville",
        "blog": "Text for Blog Id #27",
        "author":21,
        "createdAt":"2023-05-01T02:09:33.000Z",
        "status":"inactive",
        "image_path":null,
        "firstname":"Andrew",
        "lastname":"Reid"
      },
      {"id":25,
        "title":"Bottling at Three of Cups",
        "blog": "Text for Blog Id #25",
        "author":21,
        "createdAt":"2023-02-11T03:37:49.000Z",
        "status":"active",
        "image_path":null,
        "firstname":"Andrew",
        "lastname":"Reid"
      },
      {"id":22,
        "title":"January 2023",
        "blog": "Text for Blog Id #22",
        "author":21,
        "createdAt":"2023-01-19T16:15:25.000Z",
        "status":"active",
        "image_path":null,
        "firstname":"Andrew",
        "lastname":"Reid"
      },
      {"id":21,
        "title":"Mind if I ask you a question?",
        "blog": "Text for Blog Id #21",
        "author":21,
        "createdAt":"2022-11-21T23:38:03.000Z",
        "status":"active",
        "image_path":null,
        "firstname":"Andrew",
        "lastname":"Reid"
      },
      {"id":20,
        "title":"Pumpkin Contest 2022!!!",
        "blog": "Text for Blog Id #20",
        "author":21,
        "createdAt":"2022-10-18T23:21:34.000Z",
        "status":"active",
        "image_path":null,
        "firstname":"Andrew",
        "lastname":"Reid"
      },
      {"id":19,
        "title":"How I Built This",
        "blog": "Text for Blog Id #19",
        "author":21,
        "createdAt":"2022-10-13T17:08:26.000Z",
        "status":"active",
        "image_path":null,
        "firstname":"Andrew",
        "lastname":"Reid"
      },
      {"id":16,
        "title":"Summer Vacation 2022",
        "blog": "Text for Blog Id #16",
        "author":21,
        "createdAt":"2022-09-26T22:14:09.000Z",
        "status":"active",
        "image_path":null,
        "firstname":"Andrew",
        "lastname":"Reid"
      },
      {"id":13,
        "title":"How are we going to do this?",
        "blog": "Text for Blog Id #13",
        "author":21,
        "createdAt":"2022-05-25T14:15:13.000Z",
        "status":"active",
        "image_path":null,
        "firstname":"Andrew",
        "lastname":"Reid"
      },
      {"id":12,
        "title":"Major site upgrade!",
        "blog": "Text for Blog Id #12",
        "author":21,
        "createdAt":"2022-05-20T04:17:54.000Z",
        "status":"active",
        "image_path":null,
        "firstname":"Andrew",
        "lastname":"Reid"
      },
      {"id":7,
        "title":"How about a review of reviews?",
        "blog": "Text for Blog Id #7",
        "author":21,
        "createdAt":"2021-05-13T21:43:19.000Z",
        "status":"active",
        "image_path":null,
        "firstname":"Andrew",
        "lastname":"Reid"},
      {"id":6,
        "title":"Hey! Can we comment on that?",
        "blog": "Text for Blog Id #6",
        "author":21,
        "createdAt":"2021-05-06T19:53:22.000Z",
        "status":"active",
        "image_path":null,
        "firstname":"Andrew",
        "lastname":"Reid"},
      {"id":1,
        "title":"We are now bloggers!",
        "blog": "Text for Blog Id #1",
        "author":21,
        "createdAt":"2021-04-26T17:08:43.000Z",
        "status":"active",
        "image_path":null,
        "firstname":"Andrew",
        "lastname":"Reid"}
      ]},
    {"slugs":[
        {"id":1,"slug":"wildalmonds","type":"winereviews","image_path":null},
        {"id":860,"slug":"leavenworth","type":"wineregion","image_path":null},
        {"id":523,"slug":"michaelflorentino","type":"winery","image_path":"https://wildalmonds.com/api/uploads/d3e732e5-b68d-4af2-ac1e-a0b024c55e96_michael-florentino-logo-light.png"},
        {"id":833,"slug":"woodybooth","type":"photo","image_path":null},
        {"id":832,"slug":"lakechelan","type":"wineregion","image_path":null},
        {"id":601,"slug":"obelisco","type":"winery","image_path":"https://wildalmonds.com/api/uploads/e04c6c57-8919-4284-b4c2-3b1aea586d57_obelisco.PNG"},
        {"id":800,"slug":"andrewreid","type":"founder","image_path":null},
        {"id":799,"slug":"rustic","type":"winebar","image_path":"https://wildalmonds.com/api/uploads/8d394a36-d57d-4e0d-89c1-eadac8de244f_rustic_Co.jpg"},
        {"id":795,"slug":"sightglass","type":"winery","image_path":"https://images.pexels.com/photos/290316/pexels-photo-290316.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"},
        {"id":730,"slug":"twovintners","type":"winery","image_path":"https://wildalmonds.com/api/uploads/e2eb4d8e-1eff-44f1-9474-4100bc8f9978_twoVintners.jpeg"}]},
    {"videos":[
        {"video_id":11,
          "video_title":"August 2023 Wine Walks",
          "video_link":"https://youtu.be/wJHReus7rEs",
          "video_img":"https://wildalmonds.com/api/uploads/2a432b2a-5862-46ca-adcf-eac67a0c20ab_wildAlmondsLogo.jpeg",
          "uploaded":"2023-08-02T20:49:22.000Z",
          "clicks":null}]
        }],
  "error":null,
  "loading":false
}